version: "1.0"

stages:
  - "clone"
  - "report"
  - "merge"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "sereigh/abbr"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  report:
    title: Sending results..
    type: codefresh-audit-exporter
    arguments:
      CF_API_KEY: '${{CF_API_KEY}}'
      GOOGLE_STORAGE: '${{GOOGLE_STORAGE}}'
      GOOGLE_BUCKET_NAME: '${{GOOGLE_BUCKET_NAME}}'
    stage: "report"

  merge:
    title: Commiting changes and pushing to master..
    type: git-commit
    arguments:
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      git: github
      working_directory: '/codefresh/volume/${{CF_REPO_NAME}}'
      commit_message: All tests passed.
      allow_empty: false
    stage: "merge"
