version: "1.0"

stages:
  - "clone"
  - "build"
  - "test"
  - "report"
  - "merge"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "sereigh/abbr"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "sereigh/abbr"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
    registry: "dockerhub"

  test:
    title: "Running test"
    type: "freestyle"
    image: "node:12.19.0"
    working_directory: "${{clone}}"
    commands:
      - 'export COVERALLS_SERVICE_NAME=${{COVERALLS_SERVICE_NAME}}'
      - 'export COVERALLS_GIT_BRANCH=${{CF_BRANCH}}'
      - 'export COVERALLS_REPO_TOKEN=${{COVERALLS_REPO_TOKEN}}'
      - npm install --save-dev jest
      - npm run test
    stage: "test"

  report:
    title: Sending results..
    type: codefresh-audit-exporter
    arguments:
      CF_API_KEY: '${{CF_API_KEY}}'
      GOOGLE_STORAGE: '${{GOOGLE_STORAGE}}'
      GOOGLE_BUCKET_NAME: '${{GOOGLE_BUCKET_NAME}}'
    stage: "report"

  merge:
    title: Commiting changes and pushing to master..
    type: git-commit
    arguments:
      repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
      git: github
      working_directory: '/codefresh/volume/${{CF_REPO_NAME}}'
      commit_message: All tests passed.
      allow_empty: false
    stage: "merge"
